### PR TITLE
Arbitro release - updated pom and directory structure to use Arbitro name

### PR DESCRIPTION
**Pull request by bcwaters**
What does this PR do?

Prepares  arbitro-fork for release

Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged; if a component team is listed, at least one of its members needs to approve)?

@stustison @shaundmorris 

Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).

@stustison @shaundmorris 

How should this be tested?

Within DDF replace Balana-core dependency in the PDP pom with  arbitro-core. 

Any background context you want to provide?

Checklist:

 [x] Documentation Updated
 [ ] Update / Add Unit Tests
 [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by stustison** [comment]
👍

**Comment by shaundmorris** [comment]
Okay maven groupIds match what I submitted for OSSRH. Package names look good too

**Comment by shaundmorris** [comment]
Do we need a .gitignore file to take care of the .DS_Store files? I've only seen one so far

**Comment by shaundmorris** [comment]
@bcwaters we should also add in the developer information into the pom.xml file to meet the Sonatype artifact requirements

**Pull request merged**
